spring:
  application:
    name: analyzer

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


analyzer:
  kafka:
    hub-consumer:
      properties:
        bootstrap.servers: localhost:9092
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.serializer.HubEventDeserializer
        group.id: hub-group
    snapshot-consumer:
      properties:
        bootstrap.servers: localhost:9092
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.serializer.SnapshotDeserializer
        group.id: snapshot-group

