spring:
  sql:
    init: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/sh_commerce_store
    username: user_store
    password: 12345

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      hibernate.SQL: TRACE
      springframework: INFO