spring:
  sql:
    init: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart_home_commerce?currentSchema=store
    username: user
    password: 12345

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      hibernate.SQL: TRACE
      springframework: INFO